USE [master]
GO

/****** Object:  Database [RentABike]    Script Date: 28-Nov-19 8:29:32 AM ******/
CREATE DATABASE [RentABike]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RentABike', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\RentABike.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RentABike_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\RentABike_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RentABike].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RentABike] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RentABike] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RentABike] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RentABike] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RentABike] SET ARITHABORT OFF 
GO

ALTER DATABASE [RentABike] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RentABike] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RentABike] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RentABike] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RentABike] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RentABike] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RentABike] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RentABike] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RentABike] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RentABike] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RentABike] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RentABike] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RentABike] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RentABike] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RentABike] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RentABike] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RentABike] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RentABike] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RentABike] SET  MULTI_USER 
GO

ALTER DATABASE [RentABike] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RentABike] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RentABike] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RentABike] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RentABike] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RentABike] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RentABike] SET  READ_WRITE 
GO


