//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentABikeEnt : DbContext
    {
        public RentABikeEnt()
            : base("name=RentABikeEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BikeTbl> BikeTbls { get; set; }
        public virtual DbSet<TripTbl> TripTbls { get; set; }
        public virtual DbSet<UserTbl> UserTbls { get; set; }
    }
}
