//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentsTbl
    {
        public int id { get; set; }
        public Nullable<int> tripID { get; set; }
        public string cardNum { get; set; }
        public Nullable<int> cost { get; set; }
    }
}
