//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TripTbl()
        {
            this.PaymentsTbls = new HashSet<PaymentsTbl>();
        }
    
        public int id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<double> startLatitude { get; set; }
        public Nullable<double> endLatitude { get; set; }
        public Nullable<double> startLongitude { get; set; }
        public Nullable<double> endLongitude { get; set; }
        public Nullable<int> Bike { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual BikeTbl BikeTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentsTbl> PaymentsTbls { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
